### ISSUE TITLE
Tone categories in WhiteHmong

### ISSUE THREAD

**Issue by LinguList** [lexibank/wold#13]
@MacyL, the tone categories, there was a misunderstanding. what you should do is: compare words in the version of Hmong Daw with the Tones in Ratliff's version of HmongDaw and then add the Ratliff 1-8 tone to the categories. I have done so, but you have more resources, so I could not find the relevant tones. Please have a look at our file `etc/tones.tsv`, and also note the stricter normalization. We only use numbers, not the other items now (so refresh the version of wold is also important).

**Comment by Wu-Urbanek** [comment]
I tried this approach before, but then I realized that it's not completely 1 and 1 correspondences. Please allow me some time to process the code, so I can show you the general correspondence patterns
