### ISSUE TITLE
Requires a pylexibank version which is not on Pypi yet

### ISSUE THREAD

**Issue by XachaB** [lexibank/wold#18]
wold now requires a version of pylexibank which is not on Pypi yet:

https://github.com/lexibank/wold/blob/8e07ecae2fca45e6be0eee7cc40f4c68ec01000e/setup.py#L18

This causes a requirement conflict for me when pip installing wold to use in the correspondence study.

**Comment by xrotwang** [comment]
Should work now. `pylexibank 3.0.0` is released.
