### ISSUE TITLE
Please review annotation of 'll' as 'ʒ' in Imbabura Quechua.  

### ISSUE THREAD

**Issue by fractaldragonflies** [lexibank/wold#23]
My Quechua dictionary (not necessarily correct for Imbabura Quechua),  indicates that 'll' is a voiced lateral palatal fricative.  Which doesn't have a symbol on my IPA chart, but next  to 'j'. This would make it similar to the Spanish pronunciation of 'll'.

**Comment by LinguList** [comment]
We have lateral release and friction as modifying features in clts. 

```python
>>> from pyclts import CLTS
>>> bipa = CLTS().bipa
>>> bipa["with-friction voiced palatal lateral approximant consonant"].s
'ʎ͓'
>>> bipa["with-lateral-release voiced palatal fricative consonant"].s
'ʝˡ'
```

**Comment by LinguList** [comment]
Either variant would be fine with me. If you want to modify this in Quechua, this would be fine with me!

**Comment by LinguList** [comment]
On the other hand: 'ʒ' is very typical for the Spanish of Mendoza and the region. So it is not unnormal for variants of Spanish or other regions to acquire this sound for `ll` from Spanish, which is an intermediate stage of the extreme variant of unvoiced 'ʒ' in Buenos Aires.

**Comment by fractaldragonflies** [comment]
Ok. Best action seems to leave it as us. It just surprised me. And matching ‘l’ in the Aymara was more costly, but such is life! Thanks. 

J.E.M.
