### ISSUE TITLE
Map unmapped concepts

### ISSUE THREAD

**Issue by tresoldi** [lexibank/wold#3]
Some concepts (mostly language specific) are not linked but are available in Concepticon.

**Comment by xrotwang** [comment]
We don't have a built-in mechanism now to merge or add concepts with concept lists in `pylexibank`. Do you think we should have this? Alternatively, and better - I think - would be to actually add these concepts to the WOLD concept list in Concepticon, although that's a bit painful, with the number of items being baked into the IDs in Concepticon.

**Comment by LinguList** [comment]
Depends also on the concepts: if they are very rare, I would not necessarily bother now, and as wold has this fixed number of 1430 (or 1460?) concepts, any modifications in concepticon should somehow indicate that these concepts are not the primary ones, to keep the original name of the list.

**Comment by xrotwang** [comment]
As far as I know, there's already the "core meaning" flag in WOLD which flags meanings not in IDS.

**Comment by LinguList** [comment]
Yes, but I would not want to change from Haspelmath-2009-1460 to Haspelmath-2009-1498, given that these 1460 concepts are the ones usually discussed, and that this list-name was linked and used in quite a few projects and websites so far.

**Comment by LinguList** [comment]
BTW, @tresoldi, could you give some examples, please?

**Comment by tresoldi** [comment]
@natalia-morozova wanted to do this, as she will later move to the orthographic profiles (could not mention her before as she was not a contributor). 

As for concept mapping, @xrotwang is right, and our blog posts on using pyconcepticon are a good starting point: https://calc.hypotheses.org/1820

@LinguList as for examples, they are those at the bottom of https://github.com/lexibank/wold/blob/master/cldf/parameters.csv : in some cases they are missing because the gloss ("the river"), in other cases because they were added to Concepticon ("the cassava flour"). But I can see the point of not coming up with a Haspelmath-2009-1498 list, and manually adding the missing ones with the installation script does not sound so elegant. Do you prefer to leave the concept list untouched?

**Comment by LinguList** [comment]
> Each of the authors (or author teams) provided counterparts (translational equivalents) for items on a fixed list of 1,460 items, called the LWT meaning list (§3).

The addons are a result of people changing individual info in their wordlists, so you could link them to haspelmath-2009-1460, but I'd be strictly against changing the name, although this is no problem for th econcepticon, as we have other lists, like Matisoff, where the name does not reflect the number of items, as the author SAYS to use 200, but effectively uses so many a, b, and c subsections that the list is more than 210 items...

**Comment by LinguList** [comment]
But this is also "classical" concepticon practice, and the identifiers by WOLD are all with 9999, so even they reflect that this is a secondary individual meaning, non-canonical. Just wanted to make this point clear.

**Comment by tresoldi** [comment]
We could then keep the `Haspelmath-2009-1460` name/list, but including new entries, keeping the ID pattern, and trying as much as possible to only link to concepts already used in the list so we don't miss the "intralist" comparability (which is the right thing in most cases, with `"river"` and `"the river"` as equivalents).

**Comment by xrotwang** [comment]
I think @LinguList is right that these meanings/forms are another class of data in WOLD, which may even come with less quality control. So spending effort on making data comparable which was to some extent dismissed by the WOLD editors may not be worth it.

**Comment by LinguList** [comment]
It may be interesting to actually look at NUMBERS of how many "the river" is there, as opposed to "the river or stream". But if we agree that the purpose of concepticon is to share the actual wold list, as it is presented in the literature, lexibank-wold may additionally link more concepts to share the data, but with an additional concepts.csv, which would spare us the updating of concepticon here.

**Comment by tresoldi** [comment]
There 414 entries which are not mapped (of 66283, 0.6%). Guess we should drop the issue?

**Comment by LinguList** [comment]
It shows how important it is to check the dimensions of inconsistencies.
